##################上线环境################

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yueyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    data-username: root
    data-password: 123456
######### 热部署配置 #############
  devtools:
    restart:
      enabled: false # 关闭热部署
      additional-paths: src/main/java #修改那个目录下的文件需要restart